name: local_ai_summarizer
description: "Offline On-Device AI Text Summarizer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^1.6.0
  flutter_gemma_mediapipe: ^1.0.5
  llama_flutter_android: ^0.2.6
  path: ^1.9.1
  crypto: ^3.0.6
  path_provider: ^2.1.6
  sqflite: ^2.4.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - tools/model_candidate_repositories.txt

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/local_ai_lab.png"
  min_sdk_android: 26
